apiVersion: v1
kind: Pod
metadata:
  name: train-pod
spec:
  containers:
  - name: train-container
    image: adityax123/train:latest
    command: ["python3", "app.py"]
    command: ["python3", "infinite.py"]
   
  restartPolicy: Never  
